### ISSUE TITLE
could you provide a policy checkpoint 

### ISSUE THREAD

**Issue by fandulu** [Embracing/Active3DPose#1]
Thanks for your great work! 

Is offering a policy checkpoint for the following evaluation possible?
```
python run/scripts/evaluate.py --ckpt ray_results/mappo_ctcr_wdl/PPO_1bd01_00000_Feb08
```

**Comment by mickelliu** [comment]
Sure thing.

```
https://disk.pku.edu.cn/#/link/56F3EA16170527EABFA1F0497B66D1F2
Valid Until: 2023-05-05 23:59
```
You can find the model checkpoints of the control policies for 3 to 5 cams in the zip file. I did an evaluation on the Blank Environment with each model myself to save you the troubles. You can view the evaluated results with our PyQT visualizer.

**Comment by mickelliu** [comment]
FYI these models aren't trained with safety features enabled in the environment dynamics. Uncomment this block of code during evaluation to simulate random noises in actions or enforcing safe distance, etc.  

https://github.com/Embracing/Active3DPose/blob/05888366b50ad2120597b489621f1d9dbd78a5ac/run/scripts/evaluate.py#L121-L135

**Comment by fandulu** [comment]
Got it. Thanks very much.
