### ISSUE TITLE
I tried to run exec_env.py under the Active3DPose-Main but it shows ‘no module named activepose’

### ISSUE THREAD

**Issue by carolinehuang1** [Embracing/Active3DPose#3]
![WechatIMG90](https://github.com/Embracing/Active3DPose/assets/139990588/d3acf131-06f4-40a6-ab78-83b4b512c6a7)
Thanks for your great work!

I tried to run exec_env.py under the Active3DPose-Main but it shows ‘no module named activepose’

**Comment by mickelliu** [comment]
Hello. This is a problem with Python relative import. You could try run it as a script `python -m run.scripts.exec_env --binary-path PATH_TO_ENV_BINARY`

**Comment by Embracing** [comment]
You may try this command instead 'python -m run.scripts.exec_env'
